### ISSUE TITLE
System bypass bug

### ISSUE THREAD

**Issue by Darwin1546** [ASangarin/Breaker#1]
**Describe the bug**
Any player can bypass block hardness by simply hold LMB outside of the block and then move cursor on desired block.

**To Reproduce**
Hold left mouse button on air and move cursor on protected block.

**Expected behavior**
Mining fatigue to be applied, but this doesn't happen.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/63585283/91636669-07029f00-ea35-11ea-9c41-00ee055af18d.png)

**Spigot Version:**
Paper version git-Paper-243 (MC: 1.14.4)

**Plugin Version:**
BreakerLite version 1.2

**Additional context**
```
OAK_PLANKS:
  max-hardness: 60000
  states:
    woodaxe:
      type: tool
      material: WOODEN_AXE
      hardness: 59860
```
